### ISSUE TITLE
Update projects/common/packages file as a part of the build

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-distro-factory#35]
When working in a full DevOps environment, a git repository projects/common will be used.  This contains a packages file that keeps track of the current packages for the distro.  This needs updated as a part of every build to ensure that when developers do a make pull/make clone from their tooling, they are able to automatically clone new packages.  This should be done as a part of the publishing step, and be done if a config repo for the URL to this repository is set to allow operation without a full DevOps setup.

**Comment by mbelluzzo** [comment]
There is no need for a common tooling to use distro-factory.  The build is also an arguable place to update that file. Not only that, the pure existence of that file is arguable. It should be just a query to git server hosting the packages.
