### ISSUE TITLE
Build additional deltas with mixer to improve swupd update speeds

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-distro-factory#38]
Delta packs and delta manifests (from here on 'deltas' refers to both packs and manifests) should be generated for the past 10 builds to give users quick updates from releases over the past week or two.

```
mixer build delta-packs --previous-versions 10
mixer build delta-manifests --previous-versions 10
```

Additionally, for systems that are on a very old version and need to update across format bumps, need to always generate deltas from the first build in the current format to help users get to the current build faster.

```
mixer build delta-packs --from ${FIRST_BUILD}
mixer build delta-manifests --from ${FIRST_BUILD}
```

**Comment by mbelluzzo** [comment]
Fixed by: #46
