### ISSUE TITLE
Make mixer.sh work for upstreams

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-distro-factory#39]
- Do not add all upstream bundles if an upstream in `build_bundles` function
- In the `Building` section, do not automatically perform/check for a format bump if an upstream.
- If an upstream, do not log what the mix is based on
- Make sure `$clear_ver` and `$mix_ver` are the same value if an upstream
- Consolidate usage of the Clear repo and the content repo if an upstream.  Only one should be active.
- The `--offline` flag should be used everywhere

To help with conditionally performing work, create an IS_UPSTREAM flag in the config repository and key off this value.

**Comment by mbelluzzo** [comment]
This could probably be more than one task hehehe. This is a lot. (btw --offline flag does not work on a set of commands in mixer, use it only where it makes sense, it wont magically work to force only offline action on commands that ignores it which is misleading).
