### ISSUE TITLE
Add a bundles.sh interface for content.sh

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-distro-factory#40]
Content needs to be aware of all inputs to mixer.  This mean packages AND bundles.  Because content.sh has a well-defined interface with content providers, need to create a bundle provider interface and implement this.  This bundle provider interface should be able to clone bundles from a parameterized location to a defined location that will be pulled from in the mix.  Whether the mix is an upstream or a downstream will determine if the mixing process also attempt to pull bundles from an external source during the build process.

**Comment by mbelluzzo** [comment]
I don't think content.sh is just an interface for pkgs. It is an interface for all content that is input for mixer. Therefore we should move fetching the correct bundles repo there.

**Comment by mbelluzzo** [comment]
#67 partially solves this.
