### ISSUE TITLE
Generalize post processing of image files 

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-distro-factory#41]
In order to create a wider array of images with special requirements, need to generalize post processing of image files.  Rather than making assumptions about compression, make this step be a part of a finalize script.  The finalize script may also be responsible for running `qemu img-convert` on the resulting image to prepare it for publishing into the marketplace of various cloud providers.  Or it may post-process the content in the chroot to create a PXE image.  Any number of changes are possible and can be associated with the config of the image.  This allows images to be easily created in a standalone manner with the clr-installer outside of clr-distro-factory and aligns to an issue open with clr-installer: https://github.com/clearlinux/clr-installer/issues/531.  Once clr-installer closes this issue, this code will need removed from clr-distro-factory, but should be maintained until then.

**Comment by mbelluzzo** [comment]
Addressed by #55 
The only think missing now is some documentation and updating the reference config repo with at least a task and a finalize script.
