### ISSUE TITLE
Allow for an arbitrary number of content providers for packages

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-distro-factory#43]
content.sh should be able to look at a directory and add a rpm repository for each folder in the directory to mixer.  This allows users to configure any number of rpm repositories to be used as sources to support more complex downstream use cases.

**Comment by mbelluzzo** [comment]
It already allows an arbitrary number of content providers. If we want to have mixer aware of different repos when build is a different story. Even due to performance, I would prefer to have mixer only seeing at most two repos: the local repo we want and an upstream repo for downstream mixes.
